export {default as IndexView} from './IndexView'
export {default as NotFoundView} from './NotFoundView'
export {default as Faq} from './Faq'
export {default as Questionaire} from './Questionaire'
export {default as HealthForm} from './HealthForm'
